plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.2'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot 의존성
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // OpenAPI, Mail, Redis, JWT
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0"
    implementation group: "org.springframework.boot", name: "spring-boot-starter-mail", version: "3.0.5"
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'it.ozimov:embedded-redis:0.7.2'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    implementation 'org.postgresql:postgresql'


    // JPA, H2, Lombok (PostgreSQL 의존성 주석 처리, H2 의존성 추가)
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
//    implementation 'com.h2database:h2:2.1.214'  // H2 의존성 추가
    compileOnly('org.projectlombok:lombok')
    annotationProcessor('org.projectlombok:lombok')

    // Thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    // CSV & Jackson
    implementation 'com.opencsv:opencsv:5.5.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // PostgreSQL과 JSON Simple 의존성 주석 처리
    implementation 'org.postgresql:postgresql:42.6.0'
    implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1'

    // XML 처리를 위한 의존성
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
    implementation 'org.springframework:spring-oxm'
}

test {
    useJUnitPlatform()
}
