spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: choda1510@kyungmin.ac.kr
    password: xsdcxaxnwgyfswoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
springdoc:
  version: 1.0
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
jwt:
  expiration-time: 86400000
  secret: VGhlIGdyZWF0ZXN0IGdsb3J5IGluIGxpdmluZyBsaWVzIG5vdCBpbiBuZXZlciBmYWxsaW5nLCBidXQgaW4gcmlzaW5nIGV2ZXJ5IHRpbWUgd2UgZmFsbC4=
kakao:
  client_id: 0696c4ca8c9cf91931a3a54962777835
  redirect_uri: http://localhost:8080/kakao-login